# M5Stack Paper S3 Configuration

[wifi]
ssid=TeraTeams-2.4G
password=Hello189

[time]
timezone=PST8PDT
gmtoffset=-28800

[weather]
apikey=be178f4302377f8681603f30193200a0
city=Pasadena,CA,US
units=metric
